services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      NODE_ENV: production
      API_KEY: ${API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    restart: unless-stopped